version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always